force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <description
  >Messages sent between clients and Milestone Consulting team members</description>
    <label>Message</label>
    <nameField>
        <displayFormat>MSG-{0000}</displayFormat>
        <label>Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Messages</relationshipLabel>
    <relationshipName>Account_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Message Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Deleted__c.field-meta.xml
<CustomField>
    <fullName>Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description
  >Indicates if the message has been deleted by the sender. Deleted messages are not shown but are retained for reporting purposes.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Is_Read_By_Client__c.field-meta.xml
<CustomField>
    <fullName>Is_Read_By_Client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Read By Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Is_Read_By_Milestone_Team__c.field-meta.xml
<CustomField>
    <fullName>Is_Read_By_Milestone_Team__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Read By Milestone Team</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/PM_Notification_Sent__c.field-meta.xml
<CustomField>
    <fullName>PM_Notification_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PM Notification Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Recipient_Type__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Type__c</fullName>
    <label>Recipient Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Milestone Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Message__c/fields/Related_Project__c.field-meta.xml
<CustomField>
    <fullName>Related_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Messages</relationshipLabel>
    <relationshipName>Project_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Related_Task__c.field-meta.xml
<CustomField>
    <fullName>Related_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Task Messages</relationshipLabel>
    <relationshipName>Task_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sender</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sent Messages</relationshipLabel>
    <relationshipName>Sent_Messages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Message__c/fields/Visible_To_Client__c.field-meta.xml
<CustomField>
    <fullName>Visible_To_Client__c</fullName>
    <defaultValue>true</defaultValue>
    <description
  >If false, this message is only visible to Milestone Consulting team members and not to clients.</description>
    <label>Visible to Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description
  >Account associated with this project task. Links the task to the client account.</description>
    <inlineHelpText
  >Select the Account (client) that this project task is associated with. This allows you to filter and report on tasks by client.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Links a Project Task to its Project.</description>
    <inlineHelpText>Select the Project this task belongs to.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Manager responsible for overseeing this task.</description>
    <inlineHelpText>Select the Project Manager who is responsible for overseeing this task.</inlineHelpText>
    <label>Project Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Manager Tasks</relationshipLabel>
    <relationshipName>Project_Manager_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project_Task__c/fields/Related_Task__c.field-meta.xml
<CustomField>
    <fullName>Related_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related task that has a dependency relationship with this task. Used to track task dependencies and relationships.</description>
    <inlineHelpText>Select a related task if this task has a dependency on another task. Use Relationship Type to specify if it&apos;s a blocking or non-blocking dependency.</inlineHelpText>
    <label>Related Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Related Tasks</relationshipLabel>
    <relationshipName>Related_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/portal/main/default/classes/Portal/MessageNotificationSchedulerTest.cls
/**
 * Test class for MessageNotificationScheduler
 */
@isTest
private class MessageNotificationSchedulerTest {
    
    @testSetup
    static void setupTestData() {
        // Create test Account
        Account testAccount = new Account(
            Name = 'Test Client Account'
        );
        insert testAccount;
        
        // Create test Project Manager Contact
        Contact projectManager = new Contact(
            FirstName = 'Project',
            LastName = 'Manager',
            Email = 'pm@test.com',
            AccountId = testAccount.Id
        );
        insert projectManager;
        
        // Create test Client Contact
        Contact clientContact = new Contact(
            FirstName = 'Client',
            LastName = 'User',
            Email = 'client@test.com',
            AccountId = testAccount.Id
        );
        insert clientContact;
        
        // Create test Project
        Project__c testProject = new Project__c(
            Name = 'Test Project',
            Account__c = testAccount.Id
        );
        insert testProject;
        
        // Create test Task with Project Manager
        Project_Task__c testTask = new Project_Task__c(
            Name = 'Test Task',
            Project__c = testProject.Id,
            Account__c = testAccount.Id,
            Project_Manager__c = projectManager.Id
        );
        insert testTask;
        
        // Create unread message from client (older than 5 minutes)
        Message__c oldUnreadMessage = new Message__c(
            Body__c = 'Test unread message from client',
            Sender__c = clientContact.Id,
            Recipient_Type__c = 'Milestone Team',
            Related_Task__c = testTask.Id,
            Related_Project__c = testProject.Id,
            Account__c = testAccount.Id,
            Is_Read_By_Client__c = true,
            Is_Read_By_Milestone_Team__c = false,
            Visible_To_Client__c = true,
            Deleted__c = false,
            PM_Notification_Sent__c = false,
            CreatedDate = DateTime.now().addMinutes(-6) // 6 minutes ago
        );
        insert oldUnreadMessage;
        
        // Create unread message from client (less than 5 minutes - should not trigger notification)
        Message__c recentUnreadMessage = new Message__c(
            Body__c = 'Recent unread message',
            Sender__c = clientContact.Id,
            Recipient_Type__c = 'Milestone Team',
            Related_Task__c = testTask.Id,
            Related_Project__c = testProject.Id,
            Account__c = testAccount.Id,
            Is_Read_By_Client__c = true,
            Is_Read_By_Milestone_Team__c = false,
            Visible_To_Client__c = true,
            Deleted__c = false,
            PM_Notification_Sent__c = false,
            CreatedDate = DateTime.now().addMinutes(-2) // 2 minutes ago
        );
        insert recentUnreadMessage;
        
        // Create read message (should not trigger notification)
        Message__c readMessage = new Message__c(
            Body__c = 'Read message',
            Sender__c = clientContact.Id,
            Recipient_Type__c = 'Milestone Team',
            Related_Task__c = testTask.Id,
            Related_Project__c = testProject.Id,
            Account__c = testAccount.Id,
            Is_Read_By_Client__c = true,
            Is_Read_By_Milestone_Team__c = true, // Already read
            Visible_To_Client__c = true,
            Deleted__c = false,
            PM_Notification_Sent__c = false,
            CreatedDate = DateTime.now().addMinutes(-6)
        );
        insert readMessage;
        
        // Create message with notification already sent (should not trigger again)
        Message__c alreadyNotifiedMessage = new Message__c(
            Body__c = 'Already notified message',
            Sender__c = clientContact.Id,
            Recipient_Type__c = 'Milestone Team',
            Related_Task__c = testTask.Id,
            Related_Project__c = testProject.Id,
            Account__c = testAccount.Id,
            Is_Read_By_Client__c = true,
            Is_Read_By_Milestone_Team__c = false,
            Visible_To_Client__c = true,
            Deleted__c = false,
            PM_Notification_Sent__c = true, // Already sent
            CreatedDate = DateTime.now().addMinutes(-6)
        );
        insert alreadyNotifiedMessage;
    }
    
    @isTest
    static void testCheckAndSendNotifications() {
        Test.startTest();
        MessageNotificationScheduler.checkAndSendNotifications();
        Test.stopTest();
        
        // Get all messages and verify by CreatedDate
        List<Message__c> allMessages = [
            SELECT Id, PM_Notification_Sent__c, CreatedDate, Is_Read_By_Milestone_Team__c
            FROM Message__c
            ORDER BY CreatedDate DESC
        ];
        
        // Find the old unread message (should be marked as sent)
        Message__c oldUnreadMessage = null;
        Message__c recentMessage = null;
        Message__c readMessage = null;
        
        for (Message__c msg : allMessages) {
            if (msg.CreatedDate < DateTime.now().addMinutes(-5) && 
                !msg.Is_Read_By_Milestone_Team__c && 
                oldUnreadMessage == null) {
                oldUnreadMessage = msg;
            } else if (msg.CreatedDate > DateTime.now().addMinutes(-5) && 
                       !msg.Is_Read_By_Milestone_Team__c && 
                       recentMessage == null) {
                recentMessage = msg;
            } else if (msg.Is_Read_By_Milestone_Team__c && readMessage == null) {
                readMessage = msg;
            }
        }
        
        // Verify that the old unread message was marked as notification sent
        if (oldUnreadMessage != null) {
            System.assertEquals(true, oldUnreadMessage.PM_Notification_Sent__c, 
                'Old unread message should be marked as notification sent');
        }
        
        // Verify recent message was not marked (it's less than 5 minutes old)
        if (recentMessage != null) {
            System.assertEquals(false, recentMessage.PM_Notification_Sent__c, 
                'Recent message should not be marked as notification sent');
        }
        
        // Verify read message was not marked
        if (readMessage != null) {
            System.assertEquals(false, readMessage.PM_Notification_Sent__c, 
                'Read message should not be marked as notification sent');
        }
    }
    
    @isTest
    static void testScheduledExecution() {
        Test.startTest();
        MessageNotificationScheduler scheduler = new MessageNotificationScheduler();
        String jobId = System.schedule('Test Message Notification', '0 0 * * * ?', scheduler);
        Test.stopTest();
        
        // Verify job was scheduled
        System.assertNotEquals(null, jobId, 'Job should be scheduled');
        
        // Verify the execute method can be called
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobId];
        System.assertEquals('0 0 * * * ?', ct.CronExpression, 'Cron expression should match');
    }
    
    @isTest
    static void testMessageWithoutProjectManager() {
        // Create message with task that has no project manager
        Account testAccount = [SELECT Id FROM Account LIMIT 1];
        Contact clientContact = [SELECT Id FROM Contact WHERE Email = 'client@test.com' LIMIT 1];
        Project__c testProject = [SELECT Id FROM Project__c LIMIT 1];
        
        Project_Task__c taskWithoutPM = new Project_Task__c(
            Name = 'Task Without PM',
            Project__c = testProject.Id,
            Account__c = testAccount.Id,
            Project_Manager__c = null // No project manager
        );
        insert taskWithoutPM;
        
        Message__c messageWithoutPM = new Message__c(
            Body__c = 'Message without PM',
            Sender__c = clientContact.Id,
            Recipient_Type__c = 'Milestone Team',
            Related_Task__c = taskWithoutPM.Id,
            Related_Project__c = testProject.Id,
            Account__c = testAccount.Id,
            Is_Read_By_Client__c = true,
            Is_Read_By_Milestone_Team__c = false,
            Visible_To_Client__c = true,
            Deleted__c = false,
            PM_Notification_Sent__c = false,
            CreatedDate = DateTime.now().addMinutes(-6)
        );
        insert messageWithoutPM;
        
        Test.startTest();
        MessageNotificationScheduler.checkAndSendNotifications();
        Test.stopTest();
        
        // Verify message was marked as sent (to avoid checking repeatedly) even though no email was sent
        Message__c updatedMessage = [
            SELECT Id, PM_Notification_Sent__c
            FROM Message__c
            WHERE Id = :messageWithoutPM.Id
        ];
        
        System.assertEquals(true, updatedMessage.PM_Notification_Sent__c, 
            'Message without PM should be marked as sent to avoid repeated checks');
    }
}